# This is a basic workflow to help you get started with Actions

name: Calculate COVID Stats

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  calculate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - run: |
        ruby scripts/stats_by_county.rb
        git config --global user.email "ian@iancanderson.com"
        git config --global user.name "Ian C. Anderson"
        git add stats_by_county.md
        git commit -m "Update stats_by_county.md"
        git push origin HEAD:master
