name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PUBLIC_REPO_PAT}}
      - name: Merge upstream
        run: |
          git config --global user.name 'Ian Anderson'
          git config --global user.email 'ian@iancanderson.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/nytimes/covid-19-data.git
          git fetch upstream

          git merge --no-edit upstream/master
          git push origin master
